---
- apt_repository:
    repo: ppa:ondrej/php

- name: Install php-fpm with modules
  apt: name={{item}} state=present
  with_items:
       - php{{php_version}}-cli
       - php{{php_version}}-common
       - php{{php_version}}-mysql
       - php{{php_version}}-gd
       - php{{php_version}}-fpm
       - php{{php_version}}-cgi
       - php-pear
       - php{{php_version}}-mcrypt
       - php{{php_version}}-mbstring

- name: Configure fpm pool
  ini_file:
    path=/etc/php/5.6/fpm/pool.d/www.conf
    section=www
    option=listen
    value=127.0.0.1:9000
    backup=yes
  notify:
    - restart php-fpm

- name: Replace host name in the database
  shell: "php /vagrant/vendor/Search-Replace-DB/srdb.cli.php -h 127.0.0.1 -u root -p '' -n digital9_prod -s 'http://digitalsubstation.com' -r 'http://localhost:30080'"
  args:
    chdir: /vagrant/vendor/Search-Replace-DB