---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy across new nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf

- name: Remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Copy site configuration
  template:
    src=cps.conf.j2
    dest=/etc/nginx/sites-available/cps.conf

- name: Create a symlink
  file:
    src=/etc/nginx/sites-available/cps.conf
    dest=/etc/nginx/sites-enabled/cps
    state=link
  notify:
    - restart nginx